on: [push]
jobs:
  debug:
    runs-on: podman
    container:  
      image: docker.io/library/alpine 
    defaults:
      run:
        working-directory: .
    steps:
      - name: "show env"
        run:
          env|sort
      - name: "show home"
        run: |
          pwd
          help
          ls -la
