on: [push]
jobs:
  demoshell:
    runs-on: fc42dev
    defaults:
      run:
        working-directory: .
    steps:
      - name: show env
        run: |
          id
          pwd
          alias
          env|sort
      - name: show home
        run: |
          cd ~
          ls -la
      - name: podman info
        run: podman info
      - name: docker info
        run: docker info
      - name: podman, docker images
        run: |
          podman images
          docker images
